version: '3'

services:
  hello-world-service:
    build: .
    command: ./.docker/entrypoint.sh
    container_name: grpc-nestjs-hello-world-service
    ports:
      - 50053:50052
      #- 9229:9229
    volumes:
      - .:/home/node/service
    extra_hosts: 
        - 'host.docker.internal:172.17.0.1'